CREATE DATABASE IF NOT EXISTS gaestebuch_demo
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE gaestebuch_demo;

CREATE TABLE IF NOT EXISTS gaestebuch (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(60) NOT NULL,
  nachricht TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;
